### ISSUE TITLE
希望能适配更多应用

### ISSUE THREAD

**Issue by OctoSheep** [singleNeuron/XposedMusicNotify#17]
希望老哥能适配更多应用，或者提供适配的方法也行，我个人常用的 Spotify, Apple Music 和 QQ 音乐都没有适配，在 Flyme 上都有白边（去白边开关已开），一开始还以为是 Bug，看了看说明才知道没适配🙃
![S00726-12511334](https://user-images.githubusercontent.com/30658014/88471806-d57f4b00-cf3f-11ea-9437-65594f5d05c0.png)

**Comment by Cryolitia** [comment]
@ZyyMaker 白边不是因为没适配啊，无效才是因为没适配…去白边没用的话建议去试一下我单独写的去白边模块
https://github.com/singleNeuron/XposedRemoveNotificationWhiteFrame

**Comment by ZyyMaker** [comment]
@singleNeuron 感谢感谢，现在可以了
![S00726-13560572](https://user-images.githubusercontent.com/30658014/88472688-2e52e180-cf48-11ea-81f8-aee47f871e65.png)
但没有圆角看起来比较突兀😅如果可以调整圆角大小的话，那就完美啦，感谢大佬
