### ISSUE TITLE
切歌的时候会有一个弹出通知

### ISSUE THREAD

**Issue by JIANG-KING** [singleNeuron/XposedMusicNotify#4]
手机机型mi9，MIUI 10，9.8.2，安卓q

**Comment by Cryolitia** [comment]
由于targetSdkVersion升高导致应用行为发生变化，非模块本身问题，可以在软件设置里选择Music/音乐通知Channel自定义音乐通知的相关显示方式。我会进一步关注此方面问题并尽量改善用户体验，感谢您的使用和反馈。
![Screenshot_2019-09-20-20-30-47-658_com android settings](https://user-images.githubusercontent.com/23723294/65327169-c88a2080-dbe5-11e9-851e-89533cbb6c59.jpg)
