### ISSUE TITLE
增加哔哩哔哩支持

### ISSUE THREAD

**Issue by HinataKato** [singleNeuron/XposedMusicNotify#8]
如题。

**Comment by Cryolitia** [comment]
![Screenshot_2019-11-12-08-17-37-972_tv danmaku bili](https://user-images.githubusercontent.com/23723294/68650309-f7a57a00-0524-11ea-9801-3016db317168.jpg)
支持bilibili，请在b站客户端中将通知栏样式设为z系统样式

**Comment by HinataKato** [comment]
> ![Screenshot_2019-11-12-08-17-37-972_tv danmaku bili](https://user-images.githubusercontent.com/23723294/68650309-f7a57a00-0524-11ea-9801-3016db317168.jpg)
> 支持bilibili，请在b站客户端中将通知栏样式设为z系统样式
 
![Screenshot_2019-11-14-00-47-14-717_cn nexus6p QQMusicNotify](https://user-images.githubusercontent.com/57648531/68784982-65ae8600-0678-11ea-93fe-52f1bf3e7906.jpg)
![result-2019-11-14-00-49-51](https://user-images.githubusercontent.com/57648531/68785149-b0c89900-0678-11ea-9669-8d2a93ebe5b5.png)
那我大概用了个假的

**Comment by Cryolitia** [comment]
这个不需要在播放器设置的界面里显示，没有是很正常的，请问您的插件版本以及网易云音乐是否正常

**Comment by HinataKato** [comment]
> 这个不需要在播放器设置的界面里显示，没有是很正常的，请问您的插件版本以及网易云音乐是否正常

2.7.1  MIUI11 Android 10 网易云显示正常
![Screenshot_2019-11-14-00-56-20-435_bitpit launcher](https://user-images.githubusercontent.com/57648531/68785762-9d69fd80-0679-11ea-8e9a-168f4d9ba994.jpg)

**Comment by Cryolitia** [comment]
看看给没给哔哩哔哩读取外置存储的权限，或者换2.7.0并关闭SELinux试试

**Comment by HinataKato** [comment]
> 看看给没给哔哩哔哩读取外置存储的权限，或者换2.7.0并关闭SELinux试试

开了存储重定向 是需要给哔哩哔哩读取配置文件的权限吗？

**Comment by Cryolitia** [comment]
显然是的...而且插件的首页故障排除里就有很明显的提示。如果问题解决请自行关闭issue。

**Comment by HinataKato** [comment]
> 显然是的...而且插件的首页故障排除里就有很明显的提示。如果问题解决请自行关闭issue。

是我智障了 还以为是不支持哔哩哔哩的（（
