### ISSUE TITLE
添加支持该应用的提示

### ISSUE THREAD

**Issue by HinataKato** [singleNeuron/XposedMusicNotify#9]
如题 提示一下支持这个应用 不提示 开了重定向 根本不知道支持这个应用

**Comment by Cryolitia** [comment]
![Screenshot_2019-11-13-18-55-49-319_com tencent mobileqq](https://user-images.githubusercontent.com/23723294/68790268-45b29e80-0647-11ea-826b-86ff89e8f902.jpg)
